"""Reference generation and robust controller for the manipulator."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .config import (
    PlannerConfig,
    RobustControllerConfig,
    TargetConfig,
)
from .system import PlanarArm, angle_error, wrap_angles


@dataclass(frozen=True)
class ReferenceState:
    """Desired trajectory generated by the planner.

    In the lecture notation this is the desired signal q_d. The filtered
    reference q_r is built inside the controllers from q_d and the tracking
    error.
    """

    q: np.ndarray
    dq: np.ndarray
    ddq: np.ndarray
    target: np.ndarray
    target_velocity: np.ndarray


@dataclass(frozen=True)
class ControlInfo:
    tau_raw: np.ndarray
    tau: np.ndarray
    q_error: np.ndarray
    dq_error: np.ndarray
    sliding_error: np.ndarray
    q_model: np.ndarray
    dq_model: np.ndarray
    ddq_model: np.ndarray
    dq_r: np.ndarray
    ddq_r: np.ndarray
    inertia_hat: np.ndarray
    damping_hat: np.ndarray
    bias_hat: np.ndarray
    saturated: bool


class JointReferenceModel:
    def __init__(self, omega_n: float, zeta: float, dt: float) -> None:
        self.wn2 = float(omega_n) ** 2
        self.two_zeta_wn = 2.0 * float(zeta) * float(omega_n)
        self.dt = float(dt)
        self.q_m = 0.0
        self.dq_m = 0.0
        self.ddq_m = 0.0
        self.initialized = False

    def reset(self, q0: float = 0.0, dq0: float = 0.0, ddq0: float = 0.0) -> None:
        self.q_m = float(q0)
        self.dq_m = float(dq0)
        self.ddq_m = float(ddq0)
        self.initialized = True

    def step(self, r: float) -> tuple[float, float, float]:
        angle_error = float(wrap_angles(float(r) - self.q_m))
        self.ddq_m = self.wn2 * angle_error - self.two_zeta_wn * self.dq_m
        self.dq_m += self.ddq_m * self.dt
        self.q_m += self.dq_m * self.dt
        self.q_m = float(wrap_angles(self.q_m))
        return self.q_m, self.dq_m, self.ddq_m


class ReferenceGenerator:
    """Kinematic reference generator for the manipulator."""

    def __init__(
        self,
        *,
        arm: PlanarArm,
        target_cfg: TargetConfig,
        planner_cfg: PlannerConfig,
        q0: np.ndarray,
    ) -> None:
        self.arm = arm
        self.target_cfg = target_cfg
        self.cfg = planner_cfg
        self.q = wrap_angles(np.asarray(q0, dtype=float))
        self.dq = np.zeros_like(self.q)
        self._first_step = True

    def reset(self) -> None:
        self.q = self.arm.initial_angles.copy()
        self.dq = np.zeros_like(self.q)
        self._first_step = True

    def step(self, time: float, dt: float) -> ReferenceState:
        target = self.target_position(time)
        target_velocity = self.target_velocity(time)

        q_current = self.q.copy()
        dq_current = self.dq.copy()
        q_next, dq_next = self._next_reference(
            self.q,
            target,
            target_velocity,
            time,
            dt,
        )
        if self._first_step:
            ddq = np.zeros_like(dq_current)
            self._first_step = False
        else:
            ddq = (dq_next - dq_current) / dt
        self.q = q_next
        self.dq = dq_next
        return ReferenceState(
            q=q_current,
            dq=dq_current,
            ddq=ddq,
            target=target,
            target_velocity=target_velocity,
        )

    def target_position(self, time: float) -> np.ndarray:
        phase = self.target_cfg.omega * float(time)
        return self.target_cfg.center_xy + np.array(
            [
                self.target_cfg.amplitude_xy[0] * np.cos(phase),
                self.target_cfg.amplitude_xy[1] * np.sin(phase),
            ],
            dtype=float,
        )

    def target_velocity(self, time: float) -> np.ndarray:
        phase = self.target_cfg.omega * float(time)
        omega = self.target_cfg.omega
        return np.array(
            [
                -self.target_cfg.amplitude_xy[0] * omega * np.sin(phase),
                self.target_cfg.amplitude_xy[1] * omega * np.cos(phase),
            ],
            dtype=float,
        )

    def _next_reference(
        self,
        q: np.ndarray,
        target: np.ndarray,
        target_velocity: np.ndarray,
        time: float,
        dt: float,
    ) -> tuple[np.ndarray, np.ndarray]:
        ramp = _smooth_ramp(time, self.cfg.startup_ramp_time)
        points = self.arm.forward_kinematics(q)
        end_effector = points[-1]
        desired_task_velocity = self.cfg.goal_gain * (target - end_effector) + target_velocity
        desired_task_velocity = ramp * _limit_norm(desired_task_velocity, self.cfg.max_task_speed)

        jacobian = self.arm.point_jacobian(q, self.arm.n_joints)
        damping_matrix = (self.cfg.damping**2) * np.eye(2)
        dq = jacobian.T @ np.linalg.solve(jacobian @ jacobian.T + damping_matrix, desired_task_velocity)

        dq = np.clip(dq, -self.cfg.max_joint_speed, self.cfg.max_joint_speed)
        return wrap_angles(q + dt * dq), dq


class RobustController:
    """Robust controller with adaptive parameter estimates and sliding term."""

    name = "robust"

    def __init__(self, cfg: RobustControllerConfig, torque_limits: np.ndarray) -> None:
        self.cfg = cfg
        self.torque_limits = np.asarray(torque_limits, dtype=float)
        self.inertia_hat = cfg.initial_inertia_hat.copy()
        self.damping_hat = cfg.initial_damping_hat.copy()
        self.bias_hat = cfg.initial_bias_hat.copy()
        self.ref_models = [
            JointReferenceModel(omega_n, zeta, dt=1.0)
            for omega_n, zeta in zip(cfg.reference_model_omega_n, cfg.reference_model_zeta, strict=True)
        ]
        self.K = np.array(cfg.sliding_gain) * 2.0  # Higher gain for robustness
        self.rho = 5.0  # Robust boundary layer gain
        self.epsilon = 0.5  # Sliding surface boundary layer width

    def reset(self) -> None:
        self.inertia_hat = self.cfg.initial_inertia_hat.copy()
        self.damping_hat = self.cfg.initial_damping_hat.copy()
        self.bias_hat = self.cfg.initial_bias_hat.copy()
        for model in self.ref_models:
            model.reset()
            model.initialized = False

    def _sat(self, x: np.ndarray) -> np.ndarray:
        """Saturation function for sliding mode."""
        return np.where(
            np.abs(x) > 1.0,
            np.sign(x),
            x,
        )

    def compute(self, q: np.ndarray, dq: np.ndarray, ref: ReferenceState, dt: float) -> ControlInfo:
        q_model, dq_model, ddq_model = _step_reference_models(self.ref_models, ref, dt)
        q_error, dq_error, sliding, dq_r, ddq_r = _filtered_errors(
            q,
            dq,
            q_model,
            dq_model,
            ddq_model,
            self.cfg.lambda_gain,
        )
        inertia_hat = self.inertia_hat.copy()
        damping_hat = self.damping_hat.copy()
        bias_hat = self.bias_hat.copy()

        sat_term = self.rho * self._sat(sliding / self.epsilon)
        print(f"inertia_hat: {inertia_hat}, damping_hat: {damping_hat}, bias_hat: {bias_hat}")  # Debug print
        tau_raw = (
            inertia_hat * ddq_r
            + damping_hat * dq
            - bias_hat
            - self.K * sliding
            - sat_term
        )
        print("Controller computed tau_raw:", tau_raw)  # Debug print
        tau = np.clip(tau_raw, -self.torque_limits, self.torque_limits)

        self.inertia_hat = np.clip(
            inertia_hat + dt * (-self.cfg.gamma_inertia * sliding * ddq_r),
            self.cfg.inertia_bounds[0],
            self.cfg.inertia_bounds[1],
        )
        self.damping_hat = np.clip(
            damping_hat + dt * (-self.cfg.gamma_damping * sliding * dq),
            self.cfg.damping_bounds[0],
            self.cfg.damping_bounds[1],
        )
        self.bias_hat = np.clip(
            bias_hat + dt * (self.cfg.gamma_bias * sliding),
            self.cfg.bias_bounds[0],
            self.cfg.bias_bounds[1],
        )

        return ControlInfo(
            tau_raw=tau_raw,
            tau=tau,
            q_error=q_error,
            dq_error=dq_error,
            sliding_error=sliding,
            q_model=q_model,
            dq_model=dq_model,
            ddq_model=ddq_model,
            dq_r=dq_r,
            ddq_r=ddq_r,
            inertia_hat=inertia_hat,
            damping_hat=damping_hat,
            bias_hat=bias_hat,
            saturated=bool(np.any(np.abs(tau_raw - tau) > 1e-9)),
        )


def _filtered_errors(
    q: np.ndarray,
    dq: np.ndarray,
    q_model: np.ndarray,
    dq_model: np.ndarray,
    ddq_model: np.ndarray,
    lambda_gain: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    q_error = angle_error(q, q_model)
    dq_error = dq - dq_model
    sliding = dq_error + lambda_gain * q_error
    dq_r = dq_model - lambda_gain * q_error
    ddq_r = ddq_model - lambda_gain * dq_error
    return q_error, dq_error, sliding, dq_r, ddq_r


def _step_reference_models(
    ref_models: list[JointReferenceModel],
    ref: ReferenceState,
    dt: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    q_model = np.zeros_like(ref.q)
    dq_model = np.zeros_like(ref.dq)
    ddq_model = np.zeros_like(ref.ddq)
    for index, model in enumerate(ref_models):
        model.dt = float(dt)
        if not model.initialized:
            model.reset(ref.q[index], ref.dq[index], ref.ddq[index])
        q_model[index], dq_model[index], ddq_model[index] = model.step(ref.q[index])
    return q_model, dq_model, ddq_model


def _limit_norm(vector: np.ndarray, max_norm: float) -> np.ndarray:
    norm = float(np.linalg.norm(vector))
    if norm <= max_norm or norm <= 1e-12:
        return vector
    return vector * (max_norm / norm)


def _smooth_ramp(time: float, ramp_time: float) -> float:
    if ramp_time <= 1e-12:
        return 1.0
    x = min(max(float(time) / float(ramp_time), 0.0), 1.0)
    return x * x * (3.0 - 2.0 * x)
