"""Reference generation and Lyapunov/adaptive controllers."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .config import (
    AdaptiveControllerConfig,
    BacksteppingControllerConfig,
    PlannerConfig,
    RobotConfig,
    TargetConfig,
)
from .system import MovingObstacles, PlanarArm, angle_error, manipulator_terms, wrap_angles


@dataclass(frozen=True)
class ReferenceState:
    """Desired trajectory generated by the planner.

    In the lecture notation this is the desired signal q_d. The filtered
    reference q_r is built inside the controllers from q_d and the tracking
    error.
    """

    q: np.ndarray
    dq: np.ndarray
    ddq: np.ndarray
    target: np.ndarray
    target_velocity: np.ndarray
    obstacle_centers: np.ndarray
    reference_clearance: float


@dataclass(frozen=True)
class ControlInfo:
    tau_raw: np.ndarray
    tau: np.ndarray
    q_error: np.ndarray
    dq_error: np.ndarray
    sliding_error: np.ndarray
    dq_r: np.ndarray
    ddq_r: np.ndarray
    inertia_hat: np.ndarray
    damping_hat: np.ndarray
    bias_hat: np.ndarray
    mass_hat: np.ndarray
    saturated: bool


class ObstacleAwareReferenceGenerator:
    """Kinematic APF reference generator for the manipulator.

    This is a planner, not the adaptive-control proof itself. It turns the
    target and obstacle geometry into a bounded desired joint trajectory. The
    adaptive controller then tracks that trajectory.
    """

    def __init__(
        self,
        *,
        arm: PlanarArm,
        obstacles: MovingObstacles,
        target_cfg: TargetConfig,
        planner_cfg: PlannerConfig,
        q0: np.ndarray,
        obstacle_radius: float,
    ) -> None:
        self.arm = arm
        self.obstacles = obstacles
        self.target_cfg = target_cfg
        self.cfg = planner_cfg
        self.obstacle_radius = float(obstacle_radius)
        self.q = wrap_angles(np.asarray(q0, dtype=float))
        self.dq = np.zeros_like(self.q)
        self._first_step = True

    def reset(self) -> None:
        self.q = self.arm.initial_angles.copy()
        self.dq = np.zeros_like(self.q)
        self._first_step = True

    def step(self, time: float, dt: float) -> ReferenceState:
        target = self.target_position(time)
        target_velocity = self.target_velocity(time)
        obstacle_centers = self.obstacles.centers(time)

        q_current = self.q.copy()
        dq_current = self.dq.copy()
        q_next, dq_next = self._next_reference(
            self.q,
            target,
            target_velocity,
            obstacle_centers,
            time,
            dt,
        )
        if self._first_step:
            ddq = np.zeros_like(dq_current)
            self._first_step = False
        else:
            ddq = (dq_next - dq_current) / dt
        self.q = q_next
        self.dq = dq_next
        clearance = self.arm.clearance(q_current, obstacle_centers, self.obstacle_radius).min_clearance
        return ReferenceState(
            q=q_current,
            dq=dq_current,
            ddq=ddq,
            target=target,
            target_velocity=target_velocity,
            obstacle_centers=obstacle_centers,
            reference_clearance=clearance,
        )

    def target_position(self, time: float) -> np.ndarray:
        phase = self.target_cfg.omega * float(time)
        return self.target_cfg.center_xy + np.array(
            [
                self.target_cfg.amplitude_xy[0] * np.cos(phase),
                self.target_cfg.amplitude_xy[1] * np.sin(phase),
            ],
            dtype=float,
        )

    def target_velocity(self, time: float) -> np.ndarray:
        phase = self.target_cfg.omega * float(time)
        omega = self.target_cfg.omega
        return np.array(
            [
                -self.target_cfg.amplitude_xy[0] * omega * np.sin(phase),
                self.target_cfg.amplitude_xy[1] * omega * np.cos(phase),
            ],
            dtype=float,
        )

    def _next_reference(
        self,
        q: np.ndarray,
        target: np.ndarray,
        target_velocity: np.ndarray,
        obstacle_centers: np.ndarray,
        time: float,
        dt: float,
    ) -> tuple[np.ndarray, np.ndarray]:
        ramp = _smooth_ramp(time, self.cfg.startup_ramp_time)
        points = self.arm.forward_kinematics(q)
        end_effector = points[-1]
        desired_task_velocity = self.cfg.goal_gain * (target - end_effector) + target_velocity
        desired_task_velocity = ramp * _limit_norm(desired_task_velocity, self.cfg.max_task_speed)

        jacobian = self.arm.point_jacobian(q, self.arm.n_joints)
        damping_matrix = (self.cfg.damping**2) * np.eye(2)
        dq = jacobian.T @ np.linalg.solve(jacobian @ jacobian.T + damping_matrix, desired_task_velocity)

        for center in obstacle_centers:
            for link_index in range(1, self.arm.n_joints + 1):
                point = points[link_index]
                delta = point - center
                distance = float(np.linalg.norm(delta))
                clearance = distance - self.obstacle_radius - self.cfg.safe_margin
                if clearance >= self.cfg.repulsion_influence:
                    continue

                direction = delta / (distance + 1e-9)
                effective_clearance = max(clearance, 4.0)
                magnitude = (
                    self.cfg.repulsion_gain
                    * (1.0 / effective_clearance - 1.0 / self.cfg.repulsion_influence)
                    / (effective_clearance**2)
                    * self.cfg.repulsion_scale
                )
                if clearance < 0.0:
                    magnitude += self.cfg.repulsion_gain * (-clearance + 1.0) * 0.5
                point_velocity = ramp * magnitude * direction
                point_jacobian = self.arm.point_jacobian(q, link_index)
                dq += (
                    self.cfg.repulsion_joint_gain
                    * (point_jacobian.T @ point_velocity)
                    / (np.linalg.norm(point_jacobian, ord="fro") + 1e-6)
                )

        dq = np.clip(dq, -self.cfg.max_joint_speed, self.cfg.max_joint_speed)
        return wrap_angles(q + dt * dq), dq


class AdaptiveLyapunovController:
    """Slotine-Li-style adaptive controller for diagonal joint dynamics."""

    name = "adaptive"

    def __init__(self, cfg: AdaptiveControllerConfig, torque_limits: np.ndarray) -> None:
        self.cfg = cfg
        self.torque_limits = np.asarray(torque_limits, dtype=float)
        self.inertia_hat = cfg.initial_inertia_hat.copy()
        self.damping_hat = cfg.initial_damping_hat.copy()
        self.bias_hat = cfg.initial_bias_hat.copy()
        self.mass_hat = cfg.initial_mass_hat.copy()

    def reset(self) -> None:
        self.inertia_hat = self.cfg.initial_inertia_hat.copy()
        self.damping_hat = self.cfg.initial_damping_hat.copy()
        self.bias_hat = self.cfg.initial_bias_hat.copy()
        self.mass_hat = self.cfg.initial_mass_hat.copy()

    def compute(self, q: np.ndarray, dq: np.ndarray, ref: ReferenceState, dt: float) -> ControlInfo:
        q_error, dq_error, sliding, dq_r, ddq_r = _filtered_errors(
            q,
            dq,
            ref,
            self.cfg.lambda_gain,
        )
        inertia_hat = self.inertia_hat.copy()
        damping_hat = self.damping_hat.copy()
        bias_hat = self.bias_hat.copy()
        tau_raw = inertia_hat * ddq_r + damping_hat * dq - bias_hat - self.cfg.sliding_gain * sliding
        #print(tau_raw)
        tau = np.clip(tau_raw, -self.torque_limits, self.torque_limits)

        self.inertia_hat = np.clip(
            inertia_hat + dt * (-self.cfg.gamma_inertia * sliding * ddq_r),
            self.cfg.inertia_bounds[0],
            self.cfg.inertia_bounds[1],
        )
        self.damping_hat = np.clip(
            damping_hat + dt * (-self.cfg.gamma_damping * sliding * dq),
            self.cfg.damping_bounds[0],
            self.cfg.damping_bounds[1],
        )
        self.bias_hat = np.clip(
            bias_hat + dt * (self.cfg.gamma_bias * sliding),
            self.cfg.bias_bounds[0],
            self.cfg.bias_bounds[1],
        )

        return ControlInfo(
            tau_raw=tau_raw,
            tau=tau,
            q_error=q_error,
            dq_error=dq_error,
            sliding_error=sliding,
            dq_r=dq_r,
            ddq_r=ddq_r,
            inertia_hat=inertia_hat,
            damping_hat=damping_hat,
            bias_hat=bias_hat,
            mass_hat=np.full_like(q, np.nan, dtype=float),
            saturated=bool(np.any(np.abs(tau_raw - tau) > 1e-9)),
        )


AdaptiveController = AdaptiveLyapunovController


class AdaptiveSimplifiedController:
    """Adaptive backstepping with simplified model: diagonal inertia, C=0, G(q, m_hat)."""

    name = "adaptive_simp"

    def __init__(
        self,
        cfg: AdaptiveControllerConfig,
        robot_cfg: RobotConfig,
        torque_limits: np.ndarray,
        backstepping_cfg: BacksteppingControllerConfig | None = None,
    ) -> None:
        self.cfg = cfg
        self.link_lengths = np.asarray(robot_cfg.link_lengths, dtype=float)
        self.torque_limits = np.asarray(torque_limits, dtype=float)
        self.inertia_hat = cfg.initial_inertia_hat.copy()
        self.damping_hat = cfg.initial_damping_hat.copy()
        self.mass_hat = cfg.initial_mass_hat.copy()
        if backstepping_cfg is None:
            self.k1 = np.eye(self.inertia_hat.size) * float(cfg.lambda_gain)
            self.k2 = np.diag(np.asarray(cfg.sliding_gain, dtype=float))
        else:
            self.k1 = np.diag(np.asarray(backstepping_cfg.k1, dtype=float))
            self.k2 = np.diag(np.asarray(backstepping_cfg.k2, dtype=float))

    def reset(self) -> None:
        self.inertia_hat = self.cfg.initial_inertia_hat.copy()
        self.damping_hat = self.cfg.initial_damping_hat.copy()
        self.mass_hat = self.cfg.initial_mass_hat.copy()

    def compute(self, q: np.ndarray, dq: np.ndarray, ref: ReferenceState, dt: float) -> ControlInfo:
        inertia_hat = self.inertia_hat.copy()
        damping_hat = self.damping_hat.copy()
        mass_hat = self.mass_hat.copy()
        z1, z2, alpha_dot = _backstepping_errors(q, dq, ref, self.k1)
        desired_accel = alpha_dot - z1 - self.k2 @ z2
        M_hat_full, _, G_hat = manipulator_terms(q, dq, mass_hat, self.link_lengths)
        M_hat_diag = np.diag(M_hat_full)
        tau_raw = M_hat_diag * desired_accel + damping_hat * dq + G_hat
        tau = np.clip(tau_raw, -self.torque_limits, self.torque_limits)

        gravity_regressor = _gravity_mass_regressor(q, self.link_lengths)
        self.inertia_hat = M_hat_diag.copy()
        self.damping_hat = np.clip(
            damping_hat + dt * (-self.cfg.gamma_damping * z2 * dq),
            self.cfg.damping_bounds[0],
            self.cfg.damping_bounds[1],
        )
        self.mass_hat = np.clip(
            mass_hat + dt * (-self.cfg.gamma_mass * (gravity_regressor.T @ z2)),
            self.cfg.mass_bounds[0],
            self.cfg.mass_bounds[1],
        )

        return ControlInfo(
            tau_raw=tau_raw,
            tau=tau,
            q_error=z1,
            dq_error=dq - ref.dq,
            sliding_error=z2,
            dq_r=ref.dq.copy(),
            ddq_r=ref.ddq.copy(),
            inertia_hat=M_hat_diag,
            damping_hat=damping_hat,
            bias_hat=np.zeros_like(q),
            mass_hat=mass_hat,
            saturated=bool(np.any(np.abs(tau_raw - tau) > 1e-9)),
        )


class BacksteppingFull:
    """Backstepping controller using the controller's exact nominal M, C, G model."""

    name = "backstepping_full"

    def __init__(
        self,
        cfg: BacksteppingControllerConfig,
        robot_cfg: RobotConfig,
        torque_limits: np.ndarray,
    ) -> None:
        self.cfg = cfg
        self.link_lengths = np.asarray(robot_cfg.link_lengths, dtype=float)
        self.assumed_masses = np.asarray(cfg.assumed_link_masses, dtype=float)
        self.torque_limits = np.asarray(torque_limits, dtype=float)
        self.k1 = np.diag(np.asarray(cfg.k1, dtype=float))
        self.k2 = np.diag(np.asarray(cfg.k2, dtype=float))

    def reset(self) -> None:
        return None

    def compute(self, q: np.ndarray, dq: np.ndarray, ref: ReferenceState, dt: float) -> ControlInfo:
        del dt
        z1, z2, alpha_dot = _backstepping_errors(q, dq, ref, self.k1)
        M, c_times_dq, G = manipulator_terms(q, dq, self.assumed_masses, self.link_lengths)
        tau_raw = M @ (alpha_dot - z1 - self.k2 @ z2) + c_times_dq + G
        tau = np.clip(tau_raw, -self.torque_limits, self.torque_limits)
        return _backstepping_info(
            q=q,
            dq=dq,
            ref=ref,
            z1=z1,
            z2=z2,
            tau_raw=tau_raw,
            tau=tau,
            inertia_hat=np.diag(M),
            mass_hat=self.assumed_masses,
        )


class BacksteppingSimplified:
    """Backstepping controller using diagonal inertia, C=0, and nominal G(q)."""

    name = "backstepping_simp"

    def __init__(
        self,
        cfg: BacksteppingControllerConfig,
        robot_cfg: RobotConfig,
        torque_limits: np.ndarray,
    ) -> None:
        self.cfg = cfg
        self.link_lengths = np.asarray(robot_cfg.link_lengths, dtype=float)
        self.assumed_masses = np.asarray(cfg.assumed_link_masses, dtype=float)
        self.torque_limits = np.asarray(torque_limits, dtype=float)
        self.k1 = np.diag(np.asarray(cfg.k1, dtype=float))
        self.k2 = np.diag(np.asarray(cfg.k2, dtype=float))

    def reset(self) -> None:
        return None

    def compute(self, q: np.ndarray, dq: np.ndarray, ref: ReferenceState, dt: float) -> ControlInfo:
        del dt
        z1, z2, alpha_dot = _backstepping_errors(q, dq, ref, self.k1)
        M_full, _, G = manipulator_terms(q, dq, self.assumed_masses, self.link_lengths)
        M_diag = np.diag(np.diag(M_full))
        tau_raw = M_diag @ (alpha_dot - z1 - self.k2 @ z2) + G
        tau = np.clip(tau_raw, -self.torque_limits, self.torque_limits)
        return _backstepping_info(
            q=q,
            dq=dq,
            ref=ref,
            z1=z1,
            z2=z2,
            tau_raw=tau_raw,
            tau=tau,
            inertia_hat=np.diag(M_diag),
            mass_hat=self.assumed_masses,
        )


def _filtered_errors(
    q: np.ndarray,
    dq: np.ndarray,
    ref: ReferenceState,
    lambda_gain: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    q_error = angle_error(q, ref.q)
    dq_error = dq - ref.dq
    sliding = dq_error + lambda_gain * q_error
    dq_r = ref.dq - lambda_gain * q_error
    ddq_r = ref.ddq - lambda_gain * dq_error
    return q_error, dq_error, sliding, dq_r, ddq_r


def _backstepping_errors(
    q: np.ndarray,
    dq: np.ndarray,
    ref: ReferenceState,
    k1: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    z1 = angle_error(q, ref.q)
    alpha = ref.dq - k1 @ z1
    z2 = dq - alpha
    alpha_dot = ref.ddq - k1 @ (dq - ref.dq)
    return z1, z2, alpha_dot


def _backstepping_info(
    *,
    q: np.ndarray,
    dq: np.ndarray,
    ref: ReferenceState,
    z1: np.ndarray,
    z2: np.ndarray,
    tau_raw: np.ndarray,
    tau: np.ndarray,
    inertia_hat: np.ndarray,
    mass_hat: np.ndarray,
) -> ControlInfo:
    return ControlInfo(
        tau_raw=tau_raw,
        tau=tau,
        q_error=z1,
        dq_error=dq - ref.dq,
        sliding_error=z2,
        dq_r=ref.dq.copy(),
        ddq_r=ref.ddq.copy(),
        inertia_hat=inertia_hat.copy(),
        damping_hat=np.full_like(q, np.nan, dtype=float),
        bias_hat=np.full_like(q, np.nan, dtype=float),
        mass_hat=mass_hat.copy(),
        saturated=bool(np.any(np.abs(tau_raw - tau) > 1e-9)),
    )


def _gravity_mass_regressor(q: np.ndarray, link_lengths_px: np.ndarray) -> np.ndarray:
    """Return Y_g(q) such that G(q, masses) = Y_g(q) @ masses."""
    q = np.asarray(q, dtype=float)
    link_lengths_px = np.asarray(link_lengths_px, dtype=float)
    regressor = np.zeros((3, 3), dtype=float)
    for index in range(3):
        masses = np.zeros(3, dtype=float)
        masses[index] = 1.0
        _, _, gravity = manipulator_terms(q, np.zeros(3, dtype=float), masses, link_lengths_px)
        regressor[:, index] = gravity
    return regressor


def _limit_norm(vector: np.ndarray, max_norm: float) -> np.ndarray:
    norm = float(np.linalg.norm(vector))
    if norm <= max_norm or norm <= 1e-12:
        return vector
    return vector * (max_norm / norm)


def _smooth_ramp(time: float, ramp_time: float) -> float:
    if ramp_time <= 1e-12:
        return 1.0
    x = min(max(float(time) / float(ramp_time), 0.0), 1.0)
    return x * x * (3.0 - 2.0 * x)
